version: '3.2'

services:
  budget-web:
    build: client/.
    depends_on:
      - budget-server
    environment:
      BUDGET_HOST: 'http://localhost:1000'
    ports:
      - "8100:80"
  budget-server:
    build: server/.
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      SECRET: fe1a1915a379f3be5394b64d14794932
    ports:
      - "1000:1000"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27017:27017
    volumes:
      - type: "bind"
        source: "mongodb_data_volume"
        target: "/data/db"
networks:
  default:

volumes:
  mongodb_data_volume:
    external: true